In [2]:
import numpy as np

In [2]:
a = np.array(4)

In [3]:
print(a)

4


In [5]:
a.ndim

0

In [4]:
#List of tensor are called as 1D tensor also known as 1D array or simply array. 
# It also has something called axis or rank which basically means the number of dimensions.
a=np.array([1,2,3,4])
print(a)
a.ndim

[1 2 3 4]


1

In [5]:
#This 1D tensor is also called vector, when describing in terms of vector like telling the dimension of vector then it is simply the number of elements in the list is the dimension of vector
#For example from above we can say a is a 4 dimension vector because it has 4 elements.

In [6]:
#2D tensor is called matrices. This basically is the collection of multiple 1D array.
d2 = np.array([[1,2,3,4],[5,6,7,8]])
print(d2)
d2.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [7]:
#ND Tensor, are basically collection of different number of matrices
#Like a 3d tensor is basically a collection of 2d tensor
#Similarly ND tensor is basically a collection of n-d tensor
#In machine learning we generally use only 0-5 D tenssor


In [ ]:
# Some key concepts - Rank, Axis, Shape
# Rank = Number of axis = Number of dimension
# Shape - is maximum number of elements in rows, coluumns